app:
  image: "gidonan/k8s/general:49"

service:
  type: "NodePort"

mysql:
  image: "mysql:5.7"
  rootPassword: "petclinic"
  allowEmptyPassword: "true"
  user: "petclinic"
  password: "petclinic"
  database: "petclinic"

